# Generated by Django 5.0.7 on 2024-07-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0007_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
