# Generated by Django 5.0.7 on 2024-07-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0011_rename_date_submitted_feedback_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="notes",
            field=models.TextField(default="No notes"),
        ),
    ]
